# Generated by Django 5.2.6 on 2025-09-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
