# Generated by Django 5.2.6 on 2025-09-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_detector', '0003_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='detected_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
